### ISSUE TITLE
Errors in BOM/CPL

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/Module_17#10]
Replace part numbers for `Q2`, `Q3` and `SW3` and regenerate the BOM.
Make sure crossed out components (caps `C22`, `C24`, `C26`) are not in the BOM/CPL.
Add `J3` and `J11` to CPL.

**Comment by mathisschmieder** [comment]
Fixed in 6e07c9b07ef84609fef333dac708ae9ae7ddf7ba
