### ISSUE TITLE
Low decoded audio volume in rev 0.1e

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/Module_17#11]
After changing the value of the volume potentiometer from 50k to 10k, the signal at the audio amplifier's input decreased in amplitude.

Workaround: solder a 2k resistor across R31 (22k) to increase amplifier's gain.

**Comment by sp5wwp** [comment]
Fixed.

**Comment by kc1awv** [comment]
updated BOM to include changes in commit a85bac8

**Comment by hofmand** [comment]
> Workaround: solder a 2k resistor across R31 (22k) to increase amplifier's gain.

Could we get instructions for this workaround? The board I just received from Lilygo has low audio output and I don't even know where to find R31.

**Comment by sp5wwp** [comment]
I believe it's this one, should have `223` written on it.
![obraz](https://github.com/user-attachments/assets/4c405586-ff7e-40f4-9750-aada75124cd0)

**Comment by hofmand** [comment]
Thanks, the one on my board has "182" which seems correct.
