### ISSUE TITLE
License update

### ISSUE THREAD

**Issue by mdiepart** [M17-Project/Module_17#15]
We have been discussing a license change for this project. Mainly, we want to change from the TAPR Open Source Hardware License to the CC-BY-NC-SA license (version 4).

For now, the following contributors expressed their agreement with this change:
@sp5wwp 
@kc1awv 
@mathisschmieder 
@tarxvftech 

We also have identified the following contributors but haven't asked your opinion yet:
@AC4AG (under the usernames AC4AG and popracer) that contributed to the 3D printed cases for revs 0.1d and 0.1e.
@abfparts that also contributed to the 3D printed cases
@n1zzo that contributed to the drawio diagram.

Can I please ask everybody, to confirm if they agree about this license change? And more especially, could those who we haven't asked about this yet please tell us if they agree or not?

**Comment by mdiepart** [comment]
To be more accurate, we want to change the license of the repository for the revision 1 mainly. But everything in the repository will be under that license once the change is done. The previous revisions will still be under TAPR OSHL.

**Comment by tarxvftech** [comment]
I agree. I don't think I actually have copyrightable contributions but I appreciate the attention to detail in this license change.

**Comment by mdiepart** [comment]
It have finally been decided to let go of the NC clause mostly because we believe the manufacturers that want to manufacture the board will do it irrespective of the license we choose. NC clause is also refused by OSHW for their certification.
It was decided with @sp5wwp, @kc1awv and @mathisschmieder to opt for a CERN-OHL-V2-W (https://ohwr.org/cern_ohl_w_v2.txt).

Can I please ask you guys (@AC4AG, @abfparts, @tarxvftech and @n1zzo) to say here if you agree or disagree with this proposed change?
Please not that we do not ask you to bother you. You have contributed to this repository so we NEED your agreement to re-license your contributions.

If we have not received any answers by 10/12/2023 those changes will be moved to another repository.

**Comment by AC4AG** [comment]
Yes that's fine with me @abfparts is also me.

**Comment by mdiepart** [comment]
Amazing, thank you very much!

**Comment by n1zzo** [comment]
I agree about the license change!

**Comment by tarxvftech** [comment]
I agree. Furthermore if there _is_ anything in here that's actually mine, I assign copyright and ownership of everything of mine in this repo up to now to Steve KC1AWV.

**Comment by mdiepart** [comment]
Thank you all for your replies, it is much appreciated!
