### ISSUE TITLE
Add some more clearance around mounting holes

### ISSUE THREAD

**Issue by dd5xl** [M17-Project/Module_17#16]
Clearance around 3 of 4 mounting holes is not sufficient to add washers or to use a wrench to tighten the nuts.

![M17_mount_markup](https://github.com/M17-Project/Module_17/assets/7955116/6f9beece-beb0-42e6-b6f2-cd853b915559)

In case of a PCB redesign please consider to add some more clearance.

**Comment by sp5wwp** [comment]
1.0 is a complete redesign, so it should be OK then :)

**Comment by mdiepart** [comment]
Revision 1.0 has at least 1.8mm of clearance between the edge of the hole and the closest component. This clearance can be increased if opting for digital potentiometers instead of the multiturn potentiometers. Revision1.0 is also designed with a specific enclosure in mind.
