### ISSUE TITLE
Pinout of DB-9 can be wrong

### ISSUE THREAD

**Issue by pe1msz** [M17-Project/Module_17#17]
I noticed that a board I got in, has a female connector mounted, which causes some pin-numbers to be wrong.

I use a GM950 Motorola, and that seems to work great sofar (it has a data transmit and a flat audio out).

I am just wondering what the best RX-Post value is on the M17-module (allignable with a multiturn pot)

**Comment by sp5wwp** [comment]
Which pins are wrong?

For the calibration procedure, see [this](https://github.com/OpenRTX/OpenRTX/issues/184).

**Comment by pe1msz** [comment]
Pinnumbering on the DB9 was not the same as on the connector.

 

I will get more details for you.

**Comment by mdiepart** [comment]
Is this issue solved?

**Comment by kc1awv** [comment]
> I noticed that a board I got in, has a female connector mounted, which causes some pin-numbers to be wrong.

The pin numbers are always going to be the same, regardless of the connector's gender. If you're referring to the wiring diagrams provided in the repo, remember that the diagrams describe the _cable_, and not the radio/device it's plugging into.

**Comment by pe1msz** [comment]
You are right, the pins are correct! I looked at the pinout of the connector which is in the doc-folder, and that shows the front of a male connector. The board has a female connector, so i believe it would be useful to show the female connector. In my case I had the idea that the board had the wrong connector, thus having a wrong pinout.

**Comment by pe1msz** [comment]
I agree, but if you use the numbers on the picture, they are reversed as it is not the back but the front of the connector (male)

**Comment by sp5wwp** [comment]
It says "male" in the image. Closing.
