### ISSUE TITLE
Short circuit VDD to Ground 

### ISSUE THREAD

**Issue by DL6YA** [M17-Project/Module_17#18]
I uploaded the files for version r0.1e to JLCPCB the way it was described. All 10 boards have a short circuit fromm VDD to Ground. JLCPCB told me that the file for the NPTH holes should not be on the copper layer? Did someone had similar problems? Now I am afraid burning another 300$ for useless boards. 
![Uploading 001 (2).png…]()

**Comment by sp5wwp** [comment]
We are very sorry to hear this. We have ordered multiple boards ~~without facing any issues~~*. Your image did not upload, can you try again? We need more detailed info.

*I actually remember that one batch we ordered at JLCPCB had VDD shorted with GND! @kc1awv @mdiepart

**Comment by DL6YA** [comment]
Hey, it was just a production mistae. Got a new production and they work so far. Still didnt manage to make a qso, but our group is working on the cbale for there radios. hopfully we will report good news soon. are there any information about the adjustment for Rx an Tx?

**Comment by mdiepart** [comment]
Given that this was a production mishap and that the current revision is now revision 1.0, I'm gonna close this issue. 

Feel free to re-open if this happens on the new revision too :)
