### ISSUE TITLE
C22 cap in rev. 0.1c

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/Module_17#2]
C22 should be removed or replaced with a short.

**Comment by mathisschmieder** [comment]
Do you have a reason for this? We can play around with a 0R resistor instead of C22, but I'll leave the footprint in for now.

**Comment by sp5wwp** [comment]
Timer doesn't work with that cap in place. Ok, 0R works for me.

**Comment by mathisschmieder** [comment]
Ok! "Fixed" in 0.1d
