### ISSUE TITLE
M17 Rev 1.0

### ISSUE THREAD

**Issue by toshi-cxh** [M17-Project/Module_17#20]
Module 17 Revision 1.0

I was able to assemble the Main PCB and HMI PCB into the case, but the switches on the HMI board do not work properly.
Down button -- works as Enter
Right button -- works as Up
Enter button -- works as Escape
Only 3 switches respond, and the other switches, including Power, do not respond.

I assembled a second set, but the situation was the same as the first set.
The firmware written to the main board is: v0.3.7-1-g031ecda1d

Since it is not possible to write a callsign, I removed the HMI board, attached the OLED 1.3 inch module used on the previous board (Rev 0.1d/e) to the main board, and was able to set the callsign. .
The main board only seems working properly.

**Comment by toshi-cxh** [comment]
The problem is still not resolved.
After removing the device printed with "3619" mounted on U4 at JLCPCB and installing "CAP1206-1-SL" purchased from MOUSER, the 6 switches except POWER started working properly. Power is supplied from USB C.
However, when I apply 12V to the DC input and press the POWER switch, the board will not start.

**Comment by toshi-cxh** [comment]
The 3.3V regulator I ordered arrived today.  I installed it on U2, the Power switch started working properly. At the same time, the second unit was also housed in a new case (blue). When putting it in the case, I replaced the cable between the main and HMI board with a 6cm shorter cable.
Now, the assembly is finally complete.

**Comment by lemielek** [comment]
@toshi-cxh How much did you paid at JLPCB if you can share quote?

**Comment by toshi-cxh** [comment]
Hi Lemielek

I paid  USD $232.86 including shipping charge.
Order details are as follows:
5 pcs each for 4 different board, and 2 sets (No. 5 and 6) of them are
assembled by JLCPCB.
toshi[image: image.png]

2025年10月26日(日) 2:16 lemielek ***@***.***>:

**Comment by lemielek** [comment]
Thanks.
