### ISSUE TITLE
Module17_Rev_1.0.zip appears to be broken

### ISSUE THREAD

**Issue by kandev** [M17-Project/Module_17#22]
I have just tried to follow the PCB ordering guide, but the gerber files zip archive is broken and can't be opened.

**Comment by kandev** [comment]
Actually all the zip files are broken!? Are they zip files at all?

**Comment by mdiepart** [comment]
Hello,

I just tried opening those files and it works without any issue. I know several people did so too without any issue either.

We will need more details on the problems you are having but it probably does not come from the gerber archives.

**Comment by sp5wwp** [comment]
Opens with 7z with no problems (under Windows 10).

**Comment by kandev** [comment]
Tried on both Windows (integrated zip, winrar and 7zip) and in Linux with unzip - same result always:

![Screenshot 2024-10-21 100515](https://github.com/user-attachments/assets/2633c3e1-c1fc-4fd1-8d87-058191d54a85)

**Comment by mdiepart** [comment]
Are you sure you did not download the html page as an archive?

**Comment by sp5wwp** [comment]
It is an HTML page...

**Comment by mdiepart** [comment]
The link you need to use to download the archive via wget is this one: https://github.com/M17-Project/Module_17/raw/refs/heads/main/hardware/mainboard/production/Module17_Rev_1.0.zip

Closing as it is a non-issue.

**Comment by kandev** [comment]
Yup, that was it. The direct links to the files in the manual are not so direct :)
Thank you!
