### ISSUE TITLE
IC1 "Shutdown" pin

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/Module_17#3]
`Pin 1 should be connected to VDD to disable the amplifier or to GND to enable the amplifier. This pin should not be
left floating.` In our case this pin can be set either to GND or 3.3V, while the amplifier is supplied with 5V. We should add a pull-up to 5V line and drive an IRLML2060 from the micro, much like we do for the PTT_OUT line.

**Comment by mathisschmieder** [comment]
It's working perfectly fine with 3.3V, I won't change this for now.
