### ISSUE TITLE
Change OpAmp supply to 5V

### ISSUE THREAD

**Issue by mathisschmieder** [M17-Project/Module_17#5]
MCP602 (and others, probably) limit the common mode *input* voltage to Vsupply - 1.2V. We need clippy-free operation up to 3.3V to utilize all them bits, so we should supply the OpAmps with 5V.

**Comment by sp5wwp** [comment]
Can this be closed?

**Comment by mathisschmieder** [comment]
VAA was tied to 5V in 0.1d+
